### ISSUE TITLE
Ripresa i18n

### ISSUE THREAD

**Issue by Forz70043** [progit/progit2-it#11]
ciao,
ho clonato il repository, ed ho iniziato a tradurre dalla sezione **02-git-basics**, creando un nuovo branch sul mio repository locale.

Una volta terminata, aprirò qui una PR 
rimango in attesa di vostri feedback/suggerimenti
________________________________________________________________
Hi,
I've cloned this repository and started to translate from  **02-git-basics** section, created a new branch on my local repository.

When finish, i'll open here a PR.
waiting for your feedback

**Comment by danielefranceschi** [comment]
@daftano, come vogliamo coordinarci? Ad oggi tra i vari fork solo questo https://github.com/bengtsteemit/progit2-it ha un (unico) commit nella sezione `05-distributed-git`.

Io oggi stavo revisionando le istruzioni operative per la ISO9k e ci siamo resi conto che in italiano non c'è praticamente nulla.

Proposta: apriamo una issue per ogni section e ce la assegnamo?

**Comment by daftano** [comment]
@danielefranceschi il grosso del lavoro è in pratica già fatto nella versione 1. Sarebbe da:

1. Confrontare le versioni 1 e 2 inglesi per confrontare le differenze
2. Importare la versione 1
3. Tradurre le differenze tra 1 e 2 inglesi 

Fatto il primo passo poi il resto si fa in un weekend.

**Comment by danielefranceschi** [comment]
> 2. Importare la versione 1

Mi puoi dare le coordinate della v1 in italiano? Non ho trovato né tag né repo (a meno che non si tratti di [questo tuo repo](https://github.com/daftano/progit-it))

**Comment by Forz70043** [comment]
@danielefranceschi , penso si riferisca a questa [progit](https://github.com/progit/progit) .
Naturalmente è deprecata.

**Comment by daftano** [comment]
La versione 1 in italiano è https://github.com/progit/progit/tree/master/it.
Con la 2 sono cambiate un po’ di cose e i repository sono stati divisi

**Comment by Forz70043** [comment]
@danielefranceschi hai avuto modo di iniziare il confronto di versioni ?

**Comment by daftano** [comment]
Continuiamo la discussione nel gruppo (progit-it@googlegroups.com), così includiamo tutti e ci dividiamo i capitoli.
