### ISSUE TITLE
Link rotto

### ISSUE THREAD

**Issue by scompo** [progit/progit2-it#17]
Salve, volevo segnalare che aprendo il link `http://opensource.bureau-cornavin.com/glossary/index.html`, alla fine del file `README.asc`, il browser mi dice che non è possibile contattare il server.

**Comment by daftano** [comment]
Grazie Mauro per la segnalazione.

Davide

**Comment by daftano** [comment]
non sono riuscito a ritrovare il link originale, così l'ho rimosso dalla documentazione.
Riproverò con archive.org (ora anche loro hanno problemi), e magari sarò più fortunato.
